<?php

# This file was automatically generated by the MediaWiki 1.23.2
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings
# Protect against web entry
if (!defined('MEDIAWIKI')) {
  exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Media Wiki";
$wgMetaNamespace = "Media_Wiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/worlds10top.com/mediawiki1.23";
$wgScriptExtension = ".php";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://www.iwappsolutions.com";

## The relative URL path to the skins directory
$wgStylePath = "$wgScriptPath/skins";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "$wgStylePath/common/images/wiki.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "apache@www.iwappsolutions.com";
$wgPasswordSender = "apache@www.iwappsolutions.com";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "DATABASENAME";
$wgDBuser = "DB USER";
$wgDBpassword = "PASSWORD";

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=utf8";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = false;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";
# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;
## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";
# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "en";

$wgSecretKey = "SECRET KEY";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "UP GRADE KEY";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'cologneblue', 'monobook', 'vector':
$wgDefaultSkin = "vector";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";



# End of automatically generated settings.
# Add more configuration options below.

include_once ($IP . '/extensions/di/iwDrupal.php');





######################################################################
# User authentication via Drupal using AuthDrupal
# AuthDrupal v 0.7, 2010-03-01
// disable registration and sign-in from the wiki front page
$wgGroupPermissions['*']['edit'] = false; // MediaWiki 1.5+ Settings
$wgGroupPermissions['*']['createaccount'] = true; // MediaWiki 1.5+ Settings

$wgCookieDomain = 'www.iwappsolutions.com';

//
// Replace this key string with something non-trivial to prevent
// user login spoofing. Make it hardto guess, as if it is a password.
// 
// YOU MUST CHANGE THIS to something unique to your site and it must
// match this setting in Mediawiki.module
$wgAuthDrupal_security_key = 'AUTH DRUPAL SEC KEY';

// is Drupal in a different database than Mediawiki?
$wgAuthDrupal_UseExtDatabase = true;

//NOTE: You only need the next four settings if you set $wgAuthDrupal_UseExtDatabase to true.
$wgAuthDrupal_MySQL_Host = $wgDBserver;      // Drupal MySQL Host Name.
$wgAuthDrupal_MySQL_Username = $wgDBuser;        // Drupal MySQL Username.
$wgAuthDrupal_MySQL_Password = $wgDBpassword;    // Drupal MySQL Password.
$wgAuthDrupal_MySQL_Database = 'DRUPAL DB NAME';           // Drupal MySQL Database Name.

$wgAuthDrupal_TablePrefix = "";
$wgAuthDrupal_UserTable = 'users';        // name of drupal user table without prefix; normally 'users'
$wgAuthDrupal_RolesTable = 'role';       // Name of your Drupal user table. (normally 'role')
$wgAuthDrupal_UsersRolesTable = 'users_roles'; // Name of your Drupal user table. (normally 'users_roles')
// code added to use in iwDrupal.php file in extension.
$iwParameters['DrupalDBserver'] = $wgAuthDrupal_MySQL_Host;
$iwParameters['DrupalDBuser'] = $wgAuthDrupal_MySQL_Username;
$iwParameters['DrupalDBpassword'] = $wgAuthDrupal_MySQL_Password;
$iwParameters['DrupalDBname'] = $wgAuthDrupal_MySQL_Database;
//$iwParameters['DrupalDBprefix'] = "";
// $wgAuthDrupal_GetRealNames :
// Drupal's default user table schema does not include a field for real names
// If you use Drupal's profile.module and add fields profile_first_name and
// profile_last_name, the Auth Module can copy the names into the user's
// wiki profile
$wgAuthDrupal_GetRealNames = false;

// $wgAuthDrupal_PropagateRoles :
// Set this to true if you want Drupal user roles to be turned into Mediawiki
// group membership. If you want ALL roles to be turned into groups, leave
// $wgAuthDrupal_Roles empty. You can limit the roles that should be propagated 
// by setting $wgAuthDrupal_Roles to an array containing names of roles to be
// propagated, like $wgAuthDrupal_Roles = array( 'staff', 'member' );
$wgAuthDrupal_PropagateRoles = false;
$wgAuthDrupal_Roles = null;  // null means propagate all roles
// You probably do not need to change these
// $wgAuthDrupal_RealNames_fields_table; // set if different than 'profile_fields'
// $wgAuthDrupal_RealNames_values_table; // set if different than 'profile_values'
// $wgAuthDrupal_RealNames_first_name_field; // set if different than 'profile_first_name'
// $wgAuthDrupal_RealNames_last_name_field;  // set if different than 'profile_last_name'
// set to false to retain wiki's own login/logout
$wgAuthDrupal_ReplaceLogin = false;

// if ReplaceLogin is true, set these URLs to appropriate targets:
//$wgAuthDrupal_LoginURL = 'http://www.iwappsolutions.com/worlds10top.com/drupal7/?q=user/login&redirectto=http://www.iwappsolutions.com/worlds10top.com/mediawiki1.23/';
$wgAuthDrupal_LoginURL = 'http://www.iwappsolutions.com/worlds10top.com/mediawiki1.23/index.php?title=Special:UserLogin';
$wiki_url = base64_encode("http://www.iwappsolutions.com/worlds10top.com/mediawiki1.23/");
$wgAuthDrupal_LogoutURL = 'http://www.iwappsolutions.com/worlds10top.com/drupal7/?q=user/wiki/logout&mwreturn=' . $wiki_url;

// Do you want status messages in your Drupal watchdog log?
$wgAuthDrupal_LogMessages = false;

require_once 'extensions/AuthDrupal/AuthDrupal.php';
SetupAuthDrupal();

$wgPasswordSalt = false;

$wgCookieExpiration = 0;
